language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
  - release1.0
  - issue#07
notifications:
  email:
    recipients:
    - jd.liriano@alumnos.upm.es
script:
# Test
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jliriano-github -Dsonar.login=$SONAR -Dsonar.projectKey=jliriano_APAW.ECP2.JoelLiriano
